package org.eja.sisolf.entity;
// Generated 01-mar-2015 3:16:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Agente generated by hbm2java
 */
@Entity
@Table(name = "agente", catalog = "sisolf", uniqueConstraints = @UniqueConstraint(columnNames = "Email")
)
public class Agente implements java.io.Serializable {

    private Integer agenteId;
    private Cuenta cuenta;
    private String nombre;
    private String email;
    private String telefono;
    private Set<ClienteAgente> clienteAgentes = new HashSet<ClienteAgente>(0);

    public Agente() {
    }

    public Agente(Cuenta cuenta, String nombre, String email, String telefono) {
        this.cuenta = cuenta;
        this.nombre = nombre;
        this.email = email;
        this.telefono = telefono;
    }

    public Agente(Cuenta cuenta, String nombre, String email, String telefono, Set<ClienteAgente> clienteAgentes) {
        this.cuenta = cuenta;
        this.nombre = nombre;
        this.email = email;
        this.telefono = telefono;
        this.clienteAgentes = clienteAgentes;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "AgenteID", unique = true, nullable = false)
    public Integer getAgenteId() {
        return this.agenteId;
    }

    public void setAgenteId(Integer agenteId) {
        this.agenteId = agenteId;
    }

    @ManyToOne(fetch = FetchType.LAZY,cascade = {CascadeType.ALL})
    @JoinColumn(name = "CuentaID", nullable = false)
    public Cuenta getCuenta() {
        return this.cuenta;
    }

    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }

    @Column(name = "Nombre", nullable = false, length = 200)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "Email", unique = true, nullable = false, length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "Telefono", nullable = false, length = 100)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "agente")
    public Set<ClienteAgente> getClienteAgentes() {
        return this.clienteAgentes;
    }

    public void setClienteAgentes(Set<ClienteAgente> clienteAgentes) {
        this.clienteAgentes = clienteAgentes;
    }

}
