package org.eja.sisolf.entity;
// Generated 01-mar-2015 3:16:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name = "banco", catalog = "sisolf", uniqueConstraints = @UniqueConstraint(columnNames = "Institucion")
)
public class Banco implements java.io.Serializable {

    private Short bancoId;
    private String institucion;
    private String nombre;
    private String numeroAbm;
    private Set<Cuenta> cuentas = new HashSet<Cuenta>(0);

    public Banco() {
    }

    public Banco(String institucion, String nombre, String numeroAbm) {
        this.institucion = institucion;
        this.nombre = nombre;
        this.numeroAbm = numeroAbm;
    }

    public Banco(String institucion, String nombre, String numeroAbm, Set<Cuenta> cuentas) {
        this.institucion = institucion;
        this.nombre = nombre;
        this.numeroAbm = numeroAbm;
        this.cuentas = cuentas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "BancoID", unique = true, nullable = false)
    public Short getBancoId() {
        return this.bancoId;
    }

    public void setBancoId(Short bancoId) {
        this.bancoId = bancoId;
    }

    @Column(name = "Institucion", unique = true, nullable = false, length = 200)
    public String getInstitucion() {
        return this.institucion;
    }

    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }

    @Column(name = "Nombre", nullable = false, length = 200)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "NumeroABM", nullable = false, length = 3)
    public String getNumeroAbm() {
        return this.numeroAbm;
    }

    public void setNumeroAbm(String numeroAbm) {
        this.numeroAbm = numeroAbm;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
    public Set<Cuenta> getCuentas() {
        return this.cuentas;
    }

    public void setCuentas(Set<Cuenta> cuentas) {
        this.cuentas = cuentas;
    }

}
