package org.eja.sisolf.entity;
// Generated 01-mar-2015 3:16:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Configuracion generated by hbm2java
 */
@Entity
@Table(name = "configuracion", catalog = "sisolf"
)
public class Configuracion implements java.io.Serializable {

    private Integer configuracionId;
    private float iva;

    public Configuracion() {
    }

    public Configuracion(float iva) {
        this.iva = iva;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ConfiguracionID", unique = true, nullable = false)
    public Integer getConfiguracionId() {
        return this.configuracionId;
    }

    public void setConfiguracionId(Integer configuracionId) {
        this.configuracionId = configuracionId;
    }

    @Column(name = "IVA", nullable = false, precision = 6, scale = 3)
    public float getIva() {
        return this.iva;
    }

    public void setIva(float iva) {
        this.iva = iva;
    }

}
