package org.eja.sisolf.entity;
// Generated 01-mar-2015 3:16:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name = "cuenta", catalog = "sisolf"
)
public class Cuenta implements java.io.Serializable {

    private Integer cuentaId;
    private Banco banco;
    private String cuenta;
    private String clabe;
    private Set<Agente> agentes = new HashSet<Agente>(0);
    private CuentaRetorno cuentaRetorno;
    private Set<Empresa> empresas = new HashSet<Empresa>(0);

    public Cuenta() {
    }

    public Cuenta(Banco banco, String clabe) {
        this.banco = banco;
        this.clabe = clabe;
    }

    public Cuenta(Banco banco, String cuenta, String clabe, Set<Agente> agentes, CuentaRetorno cuentaRetorno, Set<Empresa> empresas) {
        this.banco = banco;
        this.cuenta = cuenta;
        this.clabe = clabe;
        this.agentes = agentes;
        this.cuentaRetorno = cuentaRetorno;
        this.empresas = empresas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "CuentaID", unique = true, nullable = false)
    public Integer getCuentaId() {
        return this.cuentaId;
    }

    public void setCuentaId(Integer cuentaId) {
        this.cuentaId = cuentaId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BancoID", nullable = false)
    public Banco getBanco() {
        return this.banco;
    }

    public void setBanco(Banco banco) {
        this.banco = banco;
    }

    @Column(name = "Cuenta", length = 15)
    public String getCuenta() {
        return this.cuenta;
    }

    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }

    @Column(name = "CLABE", nullable = false, length = 18)
    public String getClabe() {
        return this.clabe;
    }

    public void setClabe(String clabe) {
        this.clabe = clabe;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cuenta")
    public Set<Agente> getAgentes() {
        return this.agentes;
    }

    public void setAgentes(Set<Agente> agentes) {
        this.agentes = agentes;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "cuenta")
    public CuentaRetorno getCuentaRetorno() {
        return this.cuentaRetorno;
    }

    public void setCuentaRetorno(CuentaRetorno cuentaRetorno) {
        this.cuentaRetorno = cuentaRetorno;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cuenta")
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }

    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }

}
