package org.eja.sisolf.entity;
// Generated 01-mar-2015 3:16:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CuentaRetorno generated by hbm2java
 */
@Entity
@Table(name = "cuenta_retorno", catalog = "sisolf"
)
public class CuentaRetorno implements java.io.Serializable {

    private int cuentaId;
    private Cuenta cuenta;
    private SolicitudFactura solicitudFactura;
    private String nombre;

    public CuentaRetorno() {
    }

    public CuentaRetorno(Cuenta cuenta, SolicitudFactura solicitudFactura, String nombre) {
        this.cuenta = cuenta;
        this.solicitudFactura = solicitudFactura;
        this.nombre = nombre;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "cuenta"))
    @Id
    @GeneratedValue(generator = "generator")

    @Column(name = "CuentaID", unique = true, nullable = false)
    public int getCuentaId() {
        return this.cuentaId;
    }

    public void setCuentaId(int cuentaId) {
        this.cuentaId = cuentaId;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public Cuenta getCuenta() {
        return this.cuenta;
    }

    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolicitudFacturaID", nullable = false)
    public SolicitudFactura getSolicitudFactura() {
        return this.solicitudFactura;
    }

    public void setSolicitudFactura(SolicitudFactura solicitudFactura) {
        this.solicitudFactura = solicitudFactura;
    }

    @Column(name = "Nombre", nullable = false, length = 200)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
