package org.eja.sisolf.entity;
// Generated 01-mar-2015 3:16:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", catalog = "sisolf", uniqueConstraints = {
    @UniqueConstraint(columnNames = "Nombre"),
    @UniqueConstraint(columnNames = "RFC")}
)
public class Empresa implements java.io.Serializable {

    private Short empresaId;
    private Cuenta cuenta;
    private Direccion direccion;
    private String nombre;
    private String rfc;
    private String representanteLegal;
    private String giro;
    private String actividad;
    private Set<SolicitudFactura> solicitudFacturas = new HashSet<SolicitudFactura>(0);

    public Empresa() {
    }

    public Empresa(Cuenta cuenta, Direccion direccion, String nombre, String rfc, String representanteLegal, String giro, String actividad) {
        this.cuenta = cuenta;
        this.direccion = direccion;
        this.nombre = nombre;
        this.rfc = rfc;
        this.representanteLegal = representanteLegal;
        this.giro = giro;
        this.actividad = actividad;
    }

    public Empresa(Cuenta cuenta, Direccion direccion, String nombre, String rfc, String representanteLegal, String giro, String actividad, Set<SolicitudFactura> solicitudFacturas) {
        this.cuenta = cuenta;
        this.direccion = direccion;
        this.nombre = nombre;
        this.rfc = rfc;
        this.representanteLegal = representanteLegal;
        this.giro = giro;
        this.actividad = actividad;
        this.solicitudFacturas = solicitudFacturas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "EmpresaID", unique = true, nullable = false)
    public Short getEmpresaId() {
        return this.empresaId;
    }

    public void setEmpresaId(Short empresaId) {
        this.empresaId = empresaId;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.ALL})
    @JoinColumn(name = "CuentaID", nullable = false)
    public Cuenta getCuenta() {
        return this.cuenta;
    }

    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.ALL})
    @JoinColumn(name = "DireccionID", nullable = false)
    public Direccion getDireccion() {
        return this.direccion;
    }

    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }

    @Column(name = "Nombre", unique = true, nullable = false, length = 200)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "RFC", unique = true, nullable = false, length = 19)
    public String getRfc() {
        return this.rfc;
    }

    public void setRfc(String rfc) {
        this.rfc = rfc;
    }

    @Column(name = "RepresentanteLegal", nullable = false, length = 100)
    public String getRepresentanteLegal() {
        return this.representanteLegal;
    }

    public void setRepresentanteLegal(String representanteLegal) {
        this.representanteLegal = representanteLegal;
    }

    @Column(name = "Giro", nullable = false, length = 100)
    public String getGiro() {
        return this.giro;
    }

    public void setGiro(String giro) {
        this.giro = giro;
    }

    @Column(name = "Actividad", nullable = false, length = 1000)
    public String getActividad() {
        return this.actividad;
    }

    public void setActividad(String actividad) {
        this.actividad = actividad;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
    public Set<SolicitudFactura> getSolicitudFacturas() {
        return this.solicitudFacturas;
    }

    public void setSolicitudFacturas(Set<SolicitudFactura> solicitudFacturas) {
        this.solicitudFacturas = solicitudFacturas;
    }

}
