package org.eja.sisolf.entity;
// Generated 01-mar-2015 3:16:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoArchivoFactura generated by hbm2java
 */
@Entity
@Table(name = "tipo_archivo_factura", catalog = "sisolf"
)
public class TipoArchivoFactura implements java.io.Serializable {

    private Byte tipoId;
    private String tipo;
    private Set<ArchivoFactura> archivoFacturas = new HashSet<ArchivoFactura>(0);

    public TipoArchivoFactura() {
    }

    public TipoArchivoFactura(String tipo) {
        this.tipo = tipo;
    }

    public TipoArchivoFactura(String tipo, Set<ArchivoFactura> archivoFacturas) {
        this.tipo = tipo;
        this.archivoFacturas = archivoFacturas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "TipoID", unique = true, nullable = false)
    public Byte getTipoId() {
        return this.tipoId;
    }

    public void setTipoId(Byte tipoId) {
        this.tipoId = tipoId;
    }

    @Column(name = "Tipo", nullable = false, length = 45)
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoArchivoFactura")
    public Set<ArchivoFactura> getArchivoFacturas() {
        return this.archivoFacturas;
    }

    public void setArchivoFacturas(Set<ArchivoFactura> archivoFacturas) {
        this.archivoFacturas = archivoFacturas;
    }

}
